### ISSUE TITLE
[FIXED] openssl version issues

### ISSUE THREAD

**Issue by Hobbesball** [brettvitaz/mtga-wine#10]
I had issues with homebrew's latest update of openssl, which changed the PATH to the openssl lib so the build.sh didn't find an openssl installation at `/usr/local/opt/openssl/lib/libssl.1.0.0.dylib
`

If you encounter this error keeping you from installing winetricks:
`dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/bin/wget
  Reason: image not found
/usr/local/bin/winetricks: line 883: 24176 Abort trap: 6           ${torify} wget "$@"
`

the solution that worked for me was found on [this stackoverflow issue](https://stackoverflow.com/questions/59006602/dyld-library-not-loaded-usr-local-opt-openssl-lib-libssl-1-0-0-dylib):

`brew switch openssl 1.0.2s`

after switching to the old openssl installation build.sh worked just fine.

**Comment by brettvitaz** [comment]
Thank you for that report; I will look into this more closely. Though it seems like an issue outside of this project, it may be worth adding a note in the readme.

**Comment by brettvitaz** [comment]
I just did a fresh install and did not run into this issue. I would guess that removing deprecated packages and reinstalling wget would probably fix the issue as well.
