### ISSUE TITLE
MTGA only starts every second time.

### ISSUE THREAD

**Issue by DanielVolz** [brettvitaz/mtga-wine#2]
I managed to run MTGA on my macbook due your fine scripts.

Strangely I can't run the MTGA.app container by double clicking it. It only start when I execute the MTGALauncher bash script in the bin directory.

I attached the logs I could get to this post. 
The first log is from the windows debugger after the MTGA.exe crahes.
The second and third are from wine.

Here are my macbook specs:
<img width="586" alt="Screenshot 2019-08-03 at 20 15 00" src="https://user-images.githubusercontent.com/3275994/62415533-7425e400-b62b-11e9-9d5f-aca121bcf3c0.png">

[backtrace_windows_debugger.txt](https://github.com/brettvitaz/mtga-wine/files/3464174/backtrace_windows_debugger.txt)
[winelog_crash.txt](https://github.com/brettvitaz/mtga-wine/files/3464175/winelog_crash.txt)
[winelog_works.txt](https://github.com/brettvitaz/mtga-wine/files/3464176/winelog_works.txt)

**Comment by TomDemeranville** [comment]
I have the same problem.  I also had this problem when running using an older method using wineskin, if that's any help.

**Comment by brettvitaz** [comment]
I am looking into the issue related to the startup issue. It seems to be much worse with recent Arena updates, and I fear that there's not much I can do about it.

Please open a separate issue for not being able to running the MTGA app, and describe the steps you took to build/make wrapper.

**Comment by brettvitaz** [comment]
I am experimenting with fixies for the start up issue and have been unsuccessful in eliminating (or reducing) it. I will keep this issue open hoping for some insights, but I hope it will be resolved in time by subsequent Arena updates.

**Comment by brettvitaz** [comment]
Regarding the missing MTGA.app, I have overhauled and simplified the install process so that the result should be more consistent with expectations. You may now just run `Install.command` right from Finder to build the application, and the output directory will open automatically when the process completes.

**Comment by brettvitaz** [comment]
I am closing this issue because I do not believe that there is a solution I can implement in any reasonable time frame. I welcome any PRs that can resolve this issue, and if I happen across something useful, I will add a fix.
