### ISSUE TITLE
Slow graphics when playing

### ISSUE THREAD

**Issue by TomDemeranville** [brettvitaz/mtga-wine#3]
I'm not sure why, but the application runs much slower that a different (now broken) version I used with wineskin (although yours does work, which is great, so thanks!).  The interface is fine when selecting games, building decks etc, but when playing it has serious lag issues.  The stack takes forever to resolve.

I know next to nothing about wine but I am guessing there's a trick that's being missed here.  My fan isn't going as mental now, so perhaps it's not using the right graphics card.  There's also less selection in the resolutions settings.

I'm on a 2015 macbook pro with 16gb ram and an SSD.

**Comment by brettvitaz** [comment]
I am not experiencing this issue, and I am running on the same hardware you mentioned. That being said, I am looking into understanding more about how wine interacts with the Mac graphics drivers so I can improve the overall experience. 
I will continue to experiment with wine settings and try to see if there is anything that can improve performance.

**Comment by DanielVolz** [comment]
I also have the same issue as @TomDemeranville. In the menu the fps is fine but when cards or more advanced graphics are showen e.g. in the store or ingame, the fps drops to 3-7.

At this point I don't know if the problem is my old hardware or something wine related. Wild guess is directx/direct3d compatibility issues.  

Edit:

Getting these [errors](https://pastebin.com/raw/khEAL400) when I'm opening the Store (just to test the 3d performance, because the cards there require some graphics card performance).

**Comment by TomDemeranville** [comment]
It could simply be that it's using an older version of wine.

**Comment by brettvitaz** [comment]
I have overhauled the install process and switched to portable version of Wine Staging 3.21. I have seen improved performance with this version of Wine. Please try now and let me know how it works.

**Comment by brettvitaz** [comment]
Please review the readme; I have simplified the overall install procedure.

**Comment by TomDemeranville** [comment]
The change has made a huge difference.  I'd say this is now fixed.  Thanks!

**Comment by DanielVolz** [comment]
Using wine staging 3.21 also improved my fps. It still runs crappy (12 fps on average) but its much better than the wine version before and is actually playable.

@brettvitaz I have one understanding question:

Why does wine staging 4.12 not work and crashes but the older version 3.21 does work? Is wine not downwards compatible?

**Comment by brettvitaz** [comment]
@DanielVolz 
My understanding is incomplete at best, but it is related to Mac removing support for OpenGL and adding Metal, and Wine picking up support for Vulkan, which causes DirectX 9 to stop working. I recommend researching topics related to Metal, Vulkan, MoltenVK, and DXVK. 😆 
Sorry I can't be more help, but I'm still trying to understand it all.

**Comment by DanielVolz** [comment]
@brettvitaz 
Thanks for the explanation. Wine is really weird in terms of compatibility then. In my naive understanding i thought a higher version would support more and not less. 

Now I know better.
