### ISSUE TITLE
Returning, after Alt/Command-tabbing out of fullscreen results in cursor not longer being recognised

### ISSUE THREAD

**Issue by acron0** [brettvitaz/mtga-wine#4]
Repro:

* Start MTGA and set to full screen
* Press Command + Tab to minimise the game (and Wine environment)
* Click the running MTGA logo from the Dock to bring the game back to focus

Expected behaviour:

* I can hover over UI elements and press buttons

Actual behaviour:

* Although the cursor is visible, hovers and clicks are not being registered, as if the cursor messages are not being passed to the game

Workaround:

I found if I keep the game in Windowed mode, although the Wine environment itself is still "full screen", when returning to the game after a Cmd+Tab if you click the window title bar before attempting to interact with the game, cursors messages work again. It's worth mentioning, I had this exact issue with the old Wineskin.

**Comment by brettvitaz** [comment]
Thank you for the report. I have this trouble intermittently, but it usually "just works" (TM) if I don't spend too much time out of the wine application. This is a known issue related to wine and I have not been able to resolve it, other that what you have mentioned. 

I suspect that there is no resolution that I am able to deliver. I welcome any PRs that can mitigate this issue.
