### ISSUE TITLE
Problem with September 4th update for v0.1.1678 (with workaround)

### ISSUE THREAD

**Issue by joshea0** [brettvitaz/mtga-wine#5]
First off, thank you very much for publishing this awesome repo!

I just tried updating today using the provided `Updated.command` but I was unsuccessful. After a little trial and error, I was able to figure out what was going wrong and found a workaround.

## What's going wrong
It seems `Updated.command` is pulling this file: https://mtgarena.downloads.wizards.com/Live/Windows32/updates.txt to extract the location of the MSI binary to install the upgrade. However, at this time the MSIURL provided is:
```
MSIURL = https://mtgarena.downloads.wizards.com/Installers/Windows32/0.1.1678/Live/MTGAInstaller.msi
```

Which is [currently returning 404](https://mtgarena.downloads.wizards.com/Installers/Windows32/0.1.1678/Live/MTGAInstaller.msi)

## Workaround
I did some searching and found this installer link thanks to [this post on reddit](https://www.reddit.com/r/MagicArena/comments/cznktf/does_anybody_know_where_i_can_find_the_msi/eyzfs98/): https://mtgarena.downloads.wizards.com/Live/Windows32/versions/1678.727490/MTGAInstaller_0.1.1678.727490.msi

This download seemed to work, so I modified the `Updated.command` to skip checking `updates.txt` and instead just hard coded the download URL for this file like this:

```
echo "Reinstalling MTG Arena"
MTGA_INSTALLER_URL="https://mtgarena.downloads.wizards.com/Live/Windows32/versions/1678.727490/MTGAInstaller_0.1.1678.727490.msi"
MTGA_INSTALLER_BIN="MTGAInstaller_0.1.1678.727490.msi"
wget -c ${MTGA_INSTALLER_URL}
wine msiexec /x ${MTGA_INSTALLER_BIN} /qn &> /dev/null
wine msiexec /i ${MTGA_INSTALLER_BIN} /qn &> /dev/null
```

This worked for me, so I wanted to post it so hopefully others can use it too. 

I was thinking of opening a PR with this change, but I don't feel great about hard coding the URL for the MSI download. However, since the `updates.txt` published by the MTGA team seems to be incorrect at the moment, I'm not sure how to do it in a better way. Any thoughts @brettvitaz? I'm happy to clean it up and submit a PR if you let me know which direction you'd like me to go with it.

**Comment by joshea0** [comment]
I should make a quick note that after this update the game is occasionally crashing for me when entering a game. It is inconsistent - I've loaded into some games with no issue but sometimes it crashes when finding a game. So it may be safer to avoid paid entry modes right now in case you run into the same issue!

**Comment by LittlePea13** [comment]
I did the same workaround, after the same thinking process you went through, and although the update worked, I haven't been able to finish a single Brawl game, I think there is an error with some animations and the game just freezes.

**Comment by TomDemeranville** [comment]
Same.  I can update, launch, but game just crashes.

**Comment by brettvitaz** [comment]
Thank you for the report and information. I will look into this today.

**Comment by starwed** [comment]
I tried additionally updating the version of Wine to 4.0, still saw crashes trying to enter a game.

[Here's the log file after the first crash](https://gist.github.com/starwed/bc0d1ebd4e32f5517553aa33cec5d0e1).  (looks like an OOM)

I then updated to 4.15, but when built with that version the app doesn't want to open at all. 
[Here's the output from the startup crash](https://gist.github.com/starwed/5ed8fbdf56510c41958eb71828d2ee82).  (Looks like a graphics driver issue.)

**Comment by brettvitaz** [comment]
This is fixed now. I found a new way to generate the MSI Installer URL. There's a URL "https://mtgarena.downloads.wizards.com/Live/Windows32/version", which **also has a bad installer URL** (come on WoTC)!! But it has enough information to get the job done. 

Please only submit one problem per issue. It is not possible to track multiple problems in one issue.

The game play problems are worse now than ever, and I don't think that I can do anything about it. To be honest, WoTC is turning me off to Magic lately with their business practices and I don't want to invest any time in figuring that out, as I no longer play Arena. I will continue to fix issues like this, and welcome PRs that improve the project.
