### ISSUE TITLE
Current version fetching doesn't work

### ISSUE THREAD

**Issue by SalsaShark** [brettvitaz/mtga-wine#6]
It seems to be sorting the version array so [0] is the older one.

> wget -qO- https://mtgarena.downloads.wizards.com/Live/Windows32/version

{
    "VersionURL":  "https://mtgarena.downloads.wizards.com/Live/Windows32/version",
    "Versions":  {
                     "0.1.1684.728405":  "9/6/19",
                     "0.1.1678.727490":  "9/3/19"
                 },
    "CurrentPatchURL":  "https://mtgarena.downloads.wizards.com/Live/Windows32/versions/1684.728405/MTGAPatch_0.1.1684.728405.msp",
    "Flavor":  "Live",
    "ProductCode":  "{7E354BD2-3887-4E89-902C-A8A5A4C28D0B}",
    "CurrentInstallerURL":  "https://mtgarena.downloads.wizards.com/Live/Windows32/versions/1684.728405/MTGAInstaller_0.1.1684.728405.msi",
    "Name":  "MTG Arena",
    "BinaryURL":  "https://mtgarena.downloads.wizards.com/Live/Windows32/versions/",
    "FileCount":  "363"
}

> wget -qO- https://mtgarena.downloads.wizards.com/Live/Windows32/version | jq -r '.Versions | keys | .[0]'

0.1.1678.727490

> wget -qO- https://mtgarena.downloads.wizards.com/Live/Windows32/version | jq -r '.Versions | keys'

[
  "0.1.1678.727490",
  "0.1.1684.728405"
]

**Comment by brettvitaz** [comment]
Thanks for the report, I am fixing that as we speak.

It seems that the MSI URL is now correct, so I no longer need to use the version number (for now).
